export const vocabulary = [
  {
    spanish: "che",
    english: "hey/dude",
    context: "The most iconic Argentine word!",
    category: "lunfardo",
  },
  {
    spanish: "boludo/boluda",
    english: "dude/idiot (friendly)",
    context: "Used constantly among friends",
    category: "lunfardo",
  },
  {
    spanish: "Mal bicho",
    english: "bad bug",
    context: "Used to reference corrupt politicians",
    category: "lunfardo",
  },
  {
    spanish: "Hacerse el boludo",
    english: "to play dumb",
    context: "Act like you don't know",
    category: "lunfardo",
  },
  {
    spanish: "me re cabe el chabón",
    english: "I really like that guy",
    context: "Caber: to fit into, to get along well",
    category: "expressions",
  },
  {
    spanish: "cachucha",
    english: "a vagina",
    context: "literally 'cap'",
    category: "vulgar",
  },
  {
    spanish: "me da cuiqui",
    english: "to be afraid",
    context: "gives me the creeps",
    category: "expressions",
  },
  {
    spanish: "quilombo",
    english: "mess/chaos",
    context: "¡Qué quilombo! = What a mess!",
    category: "lunfardo",
  },
  {
    spanish: "laburo",
    english: "work/job",
    context: "From Italian 'lavoro'",
    category: "lunfardo",
  },
  {
    spanish: "guita",
    english: "money",
    context: "Slang for cash",
    category: "lunfardo",
  },
  {
    spanish: "chamuyar",
    english: "to sweet talk/flirt",
    context: "Trying to charm someone",
    category: "lunfardo",
  },
  {
    spanish: "chabón/chabona",
    english: "guy/girl",
    context: "Informal way to say person",
    category: "lunfardo",
  },
  {
    spanish: "pibe/piba",
    english: "kid/young person",
    context: "Very common, not offensive",
    category: "lunfardo",
  },
  {
    spanish: "fiaca",
    english: "laziness",
    context: "Me da fiaca = I'm feeling lazy",
    category: "lunfardo",
  },
  {
    spanish: "morfar",
    english: "to eat",
    context: "Vamos a morfar = Let's eat",
    category: "lunfardo",
  },
  {
    spanish: "birra",
    english: "beer",
    context: "From Italian 'birra'",
    category: "lunfardo",
  },
  {
    spanish: "bondi",
    english: "bus",
    context: "Taking the bus in Buenos Aires",
    category: "lunfardo",
  },
  {
    spanish: "mina",
    english: "girl/woman",
    context: "Old slang, still used",
    category: "lunfardo",
  },
  {
    spanish: "tipo/tipa",
    english: "guy/person",
    context: "General term for person",
    category: "lunfardo",
  },
  {
    spanish: "gil",
    english: "fool/naive person",
    context: "Can be insulting",
    category: "lunfardo",
  },
  {
    spanish: "zarpado",
    english: "over the top/crazy",
    context: "Eso está zarpado = That's crazy",
    category: "lunfardo",
  },
  {
    spanish: "copado",
    english: "cool/awesome",
    context: "Qué copado! = How cool!",
    category: "lunfardo",
  },
  {
    spanish: "trucho",
    english: "fake/counterfeit",
    context: "Es trucho = It's fake",
    category: "lunfardo",
  },
  {
    spanish: "cana",
    english: "police/cop",
    context: "Slang for police",
    category: "lunfardo",
  },
  {
    spanish: "afanar",
    english: "to steal",
    context: "Me afanaron = They robbed me",
    category: "lunfardo",
  },
  {
    spanish: "pelotudo/pelotuda",
    english: "idiot",
    context: "more offensive than boludo",
    category: "vulgar",
  },
  {
    spanish: "cagón",
    english: "a coward",
    context: "literally 'a big shit'",
    category: "vulgar",
  },
  {
    spanish: "caga de risa",
    english: "hilarious",
    context: "literally 'a shit of laughter'",
    category: "vulgar",
  },
  {
    spanish: "culo",
    english: "ass",
    context: "¡que culo!",
    category: "vulgar",
  },
  {
    spanish: "culiado",
    english: "Butt-raped",
    context: "a strong insult, 'asshole'",
    category: "vulgar",
  },
  {
    spanish: "¡cagaste!",
    english: "you fucked up",
    context: "literally 'you shat'",
    category: "vulgar",
  },
  {
    spanish: "cagada tras cagada",
    english: "one distaster after another",
    context: "literally 'one shit after another'",
    category: "vulgar",
  },
  {
    spanish: "concha",
    english: "vulgar slang term for female genitalia",
    context: "'seashell' in other Spanish dialects. Not here.",
    category: "vulgar",
  },
  {
    spanish: "¡la concha de tu madre!",
    english: "your mother's vagina",
    context: "general insult or exclamation",
    category: "vulgar",
  },
  {
    spanish: "mal cogido",
    english: "badly fucked",
    context: "someone in a bad mood",
    category: "vulgar",
  },
  {
    spanish: "hecha mierda",
    english: "made of shit",
    context: "broken, fucked up",
    category: "vulgar",
  },
  {
    spanish: "morondanga",
    english: "worthless",
    context: "something of poor quality",
    category: "lunfardo",
  },
  {
    spanish: "cara de orto",
    english: "ass-face",
    context: "insulting",
    category: "vulgar",
  },
  {
    spanish: "No me hinchés las pelotas",
    english: "don't bother me",
    context: "'stop busting my balls'",
    category: "vulgar",
  },
  {
    spanish: "¡la concha de la lora!",
    english: "the parrot's pussy",
    context: "general insult or exclamation",
    category: "vulgar",
  },
  {
    spanish: "Me chupa un huevo",
    english: "I don't care",
    context: "literally 'I suck an egg'",
    category: "expressions",
  },
  {
    spanish: "chiche bombón",
    english: "Great! Beautiful",
    context: "informal, used to praise someone's appearance",
    category: "expressions",
  },
  {
    spanish: "chorongo/a",
    english: "Poor quality, shitty",
    context: "Qué chorongo",
    category: "lunfardo",
  },
  {
    spanish: "chupa cirio",
    english: "candle sucker",
    context: "a religious fanatic, bible basher",
    category: "expressions",
  },
  {
    spanish: "colgarse",
    english: "to hang one's self",
    context: "to be spaced out, to do nothing",
    category: "lunfardo",
  },
  {
    spanish: "chamuyero",
    english: "smooth talker/know it all",
    context: "chamuyo: art of persusion",
    category: "lunfardo",
  },
  {
    spanish: "vos",
    english: "you (informal)",
    context: "Replaces 'tú' in Argentina",
    category: "voseo",
  },
  {
    spanish: "vos sos",
    english: "you are",
    context: "Instead of 'tú eres'",
    category: "voseo",
  },
  {
    spanish: "vos tenés",
    english: "you have",
    context: "Instead of 'tú tienes'",
    category: "voseo",
  },
  {
    spanish: "vos querés",
    english: "you want",
    context: "Instead of 'tú quieres'",
    category: "voseo",
  },
  {
    spanish: "vos sabés",
    english: "you know",
    context: "Instead of 'tú sabes'",
    category: "voseo",
  },
  {
    spanish: "vos podés",
    english: "you can",
    context: "Instead of 'tú puedes'",
    category: "voseo",
  },
  {
    spanish: "vos venís",
    english: "you come",
    context: "Instead of 'tú vienes'",
    category: "voseo",
  },
  {
    spanish: "¿vos entendés?",
    english: "do you understand?",
    context: "Instead of '¿tú entiendes?'",
    category: "voseo",
  },
  {
    spanish: "vos hablás",
    english: "you speak",
    context: "Instead of 'tú hablas'",
    category: "voseo",
  },
  {
    spanish: "decime",
    english: "tell me",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "mirá",
    english: "look",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "escuchá",
    english: "listen",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "esperá",
    english: "wait",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "vení",
    english: "come",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "andá",
    english: "go",
    context: "Command form with vos",
    category: "voseo",
  },
  {
    spanish: "mate",
    english: "traditional Argentine tea",
    context: "Social drink shared with friends",
    category: "culture",
  },
  {
    spanish: "asado",
    english: "barbecue",
    context: "Argentine grilling tradition",
    category: "culture",
  },
  {
    spanish: "choripán",
    english: "sausage sandwich",
    context: "Classic street food",
    category: "culture",
  },
  {
    spanish: "empanada",
    english: "stuffed pastry",
    context: "Can be baked or fried",
    category: "culture",
  },
  {
    spanish: "dulce de leche",
    english: "caramel spread",
    context: "Argentina's favorite sweet",
    category: "culture",
  },
  {
    spanish: "facturas",
    english: "pastries",
    context: "Sweet breakfast treats",
    category: "culture",
  },
  {
    spanish: "parrilla",
    english: "grill/steakhouse",
    context: "Where asado happens",
    category: "culture",
  },
  {
    spanish: "provoleta",
    english: "grilled provolone",
    context: "Melted cheese appetizer",
    category: "culture",
  },
  {
    spanish: "medialunas",
    english: "croissants",
    context: "Argentine-style croissants",
    category: "culture",
  },
  {
    spanish: "fernet con cola",
    english: "fernet with coke",
    context: "Popular Argentine cocktail",
    category: "culture",
  },
  {
    spanish: "milanesa",
    english: "breaded cutlet",
    context: "Like schnitzel",
    category: "culture",
  },
  {
    spanish: "locro",
    english: "traditional stew",
    context: "Hearty corn and meat stew",
    category: "culture",
  },
  {
    spanish: "cortado",
    english: "traditional coffee with a little milk",
    context: "literally 'cut'",
    category: "culture",
  },
  {
    spanish: "alfajor",
    english: "cookie sandwich",
    context: "Dulce de leche between cookies",
    category: "culture",
  },
  {
    spanish: "chimichurri",
    english: "herb sauce",
    context: "Goes with asado",
    category: "culture",
  },
  {
    spanish: "dale",
    english: "okay/go ahead/come on",
    context: "Multi-purpose word!",
    category: "expressions",
  },
  {
    spanish: "bárbaro",
    english: "great/awesome",
    context: "¡Qué bárbaro! = How awesome!",
    category: "expressions",
  },
  {
    spanish: "¿cómo andás?",
    english: "how are you?",
    context: "With vos conjugation",
    category: "expressions",
  },
  {
    spanish: "todo bien",
    english: "all good",
    context: "Everything's fine",
    category: "expressions",
  },
  {
    spanish: "ni ahí",
    english: "no way",
    context: "Strong disagreement",
    category: "expressions",
  },
  {
    spanish: "de una",
    english: "for sure/right away",
    context: "Absolutely yes",
    category: "expressions",
  },
  {
    spanish: "por las dudas",
    english: "just in case",
    context: "To be safe",
    category: "expressions",
  },
  {
    spanish: "la posta",
    english: "the truth",
    context: "Es la posta = That's the truth",
    category: "expressions",
  },
  {
    spanish: "no pasa nada",
    english: "no worries",
    context: "It's all good",
    category: "expressions",
  },
  {
    spanish: "re",
    english: "very/really",
    context: "Re lindo = Really nice",
    category: "expressions",
  },
  {
    spanish: "zafar",
    english: "to get by/escape",
    context: "To manage or dodge something",
    category: "expressions",
  },
  {
    spanish: "flashear",
    english: "to imagine/hallucinate",
    context: "To think crazy things",
    category: "expressions",
  },
  {
    spanish: "mala onda",
    english: "bad vibes",
    context: "Negative energy",
    category: "expressions",
  },
  {
    spanish: "buena onda",
    english: "good vibes/cool",
    context: "Positive person or situation",
    category: "expressions",
  },
  {
    spanish: "mandar fruta",
    english: "to BS/make stuff up",
    context: "Speaking without knowing",
    category: "expressions",
  },
  {
    spanish: "boludez",
    english: "nonsense/stupid thing",
    context: "Something dumb",
    category: "expressions",
  },
  {
    spanish: "al pedo",
    english: "for nothing/pointless",
    context: "Wasting time",
    category: "expressions",
  },
  {
    spanish: "estar al horno",
    english: "to be in trouble",
    context: "In a bad situation",
    category: "expressions",
  },
  {
    spanish: "ponerse las pilas",
    english: "to get going",
    context: "Get your act together",
    category: "expressions",
  },
  {
    spanish: "romper las bolas",
    english: "to break ones balls",
    context: "To bother someone (vulgar)",
    category: "expressions",
  },
  {
    spanish: "colectivo",
    english: "bus",
    context: "Public bus in Argentina",
    category: "places",
  },
  {
    spanish: "subte",
    english: "subway",
    context: "Buenos Aires metro",
    category: "places",
  },
  {
    spanish: "cancha",
    english: "field/stadium",
    context: "Where fútbol is played",
    category: "places",
  },
  {
    spanish: "vereda",
    english: "sidewalk",
    context: "Instead of 'acera'",
    category: "places",
  },
  {
    spanish: "departamento",
    english: "apartment",
    context: "Instead of 'apartamento'",
    category: "places",
  },
  {
    spanish: "kiosco",
    english: "convenience store",
    context: "Small shop",
    category: "places",
  },
  {
    spanish: "esquina",
    english: "corner",
    context: "Street corner",
    category: "places",
  },
  {
    spanish: "boliche",
    english: "nightclub",
    context: "Where to dance",
    category: "places",
  },
  {
    spanish: "fútbol",
    english: "soccer/football",
    context: "National passion!",
    category: "sports",
  },
  {
    spanish: "la pelota",
    english: "the ball",
    context: "Any ball game",
    category: "sports",
  },
  {
    spanish: "hincha",
    english: "fan",
    context: "Sports supporter",
    category: "sports",
  },
  {
    spanish: "boca",
    english: "Boca Juniors",
    context: "Football club (River is better!)",
    category: "sports",
  },
  {
    spanish: "river",
    english: "River Plate",
    context: "Famous BA football club",
    category: "sports",
  },
  {
    spanish: "messi",
    english: "Lionel Messi",
    context: "Argentina's football god",
    category: "sports",
  },
  {
    spanish: "maradona",
    english: "Diego Maradona",
    context: "Legendary footballer",
    category: "sports",
  },
  {
    spanish: "picado",
    english: "pickup game",
    context: "Casual football match",
    category: "sports",
  },
  {
    spanish: "un toque",
    english: "a bit/a moment",
    context: "Espera un toque = Wait a moment",
    category: "time",
  },
  {
    spanish: "ya",
    english: "now/already",
    context: "Ya voy = I'm coming now",
    category: "time",
  },
  {
    spanish: "recién",
    english: "just now",
    context: "Recién llegué = I just arrived",
    category: "time",
  },
  {
    spanish: "temprano",
    english: "early",
    context: "Time reference",
    category: "time",
  },
  {
    spanish: "tarde",
    english: "late/afternoon",
    context: "Time of day",
    category: "time",
  },
  {
    spanish: "lindo",
    english: "nice/pretty",
    context: "Qué día lindo = What a nice day",
    category: "weather",
  },
  {
    spanish: "frío",
    english: "cold",
    context: "Buenos Aires winters",
    category: "weather",
  },
  {
    spanish: "lluvia",
    english: "rain",
    context: "Weather condition",
    category: "weather",
  },
  {
    spanish: "pampa",
    english: "grassland plains",
    context: "Argentine landscape",
    category: "nature",
  },
  {
    spanish: "celu/celular",
    english: "cell phone",
    context: "Short form very common",
    category: "modern",
  },
  {
    spanish: "compu",
    english: "computer",
    context: "Short for computadora",
    category: "modern",
  },
  {
    spanish: "face",
    english: "Facebook",
    context: "Social media",
    category: "modern",
  },
  {
    spanish: "insta",
    english: "Instagram",
    context: "Social media",
    category: "modern",
  },
  {
    spanish: "wasa/whatsapp",
    english: "WhatsApp",
    context: "Primary messaging app",
    category: "modern",
  },
  {
    spanish: "cagado de risa",
    english: "dying of laughter",
    context: "Extremely funny (vulgar)",
    category: "emotions",
  },
  {
    spanish: "podrido",
    english: "fed up",
    context: "Estar podrido = To be sick of it",
    category: "emotions",
  },
  {
    spanish: "cagarse de frío",
    english: "freezing cold",
    context: "Very cold (vulgar)",
    category: "emotions",
  },
  {
    spanish: "embole",
    english: "boring",
    context: "Qué embole = How boring",
    category: "emotions",
  },
  {
    spanish: "palo",
    english: "million (pesos)",
    context: "Slang for 1 million",
    category: "money",
  },
  {
    spanish: "lucas",
    english: "thousand (pesos)",
    context: "Slang for 1000",
    category: "money",
  },
  {
    spanish: "mango",
    english: "peso",
    context: "No tengo un mango = I'm broke",
    category: "money",
  },
  {
    spanish: "rebaja",
    english: "sale/discount",
    context: "Shopping term",
    category: "money",
  },
  {
    spanish: "tarjeta",
    english: "card",
    context: "Credit/debit card",
    category: "money",
  },
  {
    spanish: "viejo/vieja",
    english: "old man/woman (parent)",
    context: "Affectionate for parents",
    category: "family",
  },
  {
    spanish: "hermano/hermana",
    english: "brother/sister",
    context: "Also used for close friends",
    category: "family",
  },
  {
    spanish: "novia/novio",
    english: "girlfriend/boyfriend",
    context: "Romantic partner",
    category: "family",
  },
  {
    spanish: "amigo/amiga",
    english: "friend",
    context: "Amigacho = good buddy",
    category: "family",
  },
  {
    spanish: "familia",
    english: "family",
    context: "La familia todo",
    category: "family",
  },
  {
    spanish: "tomar",
    english: "to drink/take",
    context: "Tomar mate, tomar el bondi",
    category: "verbs",
  },
  {
    spanish: "sacar",
    english: "to take out/remove",
    context: "Sacar una foto = take a photo",
    category: "verbs",
  },
  {
    spanish: "agarrar",
    english: "to grab/take",
    context: "Agarrá el bondi = Take the bus",
    category: "verbs",
  },
  {
    spanish: "bancar",
    english: "to support/tolerate",
    context: "No lo banco = I can't stand him",
    category: "verbs",
  },
  {
    spanish: "rajar",
    english: "to leave quickly",
    context: "Me rajo = I'm outta here",
    category: "verbs",
  },
  {
    spanish: "enganchar",
    english: "to hook up/catch",
    context: "Multiple meanings",
    category: "verbs",
  },
  {
    spanish: "garpar",
    english: "to pay",
    context: "Slang for paying",
    category: "verbs",
  },
  {
    spanish: "joder",
    english: "to annoy/mess with",
    context: "No me jodas = Don't mess with me",
    category: "verbs",
  },
];

export const multipleChoiceQuestions = [
  {
    question: "¡_____! ¿Cómo andás?",
    correct: "Che",
    options: ["Mate", "Asado", "Dulce", "Bondi"],
    explanation: "'Che' is the greeting - others are nouns",
  },
  {
    question: "Vamos a tomar _____ en la plaza.",
    correct: "mate",
    options: ["che", "boludo", "dale", "laburo"],
    explanation: "You 'drink' mate, not the others",
  },
  {
    question: "El domingo hacemos un _____ en casa.",
    correct: "asado",
    options: ["mate", "che", "bondi", "subte"],
    explanation: "You 'make' an asado (BBQ), not the others",
  },
  {
    question: "_____, voy para allá.",
    correct: "Dale",
    options: ["Mate", "Pibe", "Mina", "Cana"],
    explanation: "'Dale' means okay/alright - others are nouns",
  },
  {
    question: "Este restaurant es re _____.",
    correct: "copado",
    options: ["mate", "bondi", "asado", "subte"],
    explanation: "'Copado' is an adjective (cool) - others are nouns",
  },
  {
    question: "Che _____, ¿qué hacés?",
    correct: "boludo",
    options: ["mate", "asado", "dale", "quilombo"],
    explanation: "'Boludo' addresses a person - others don't fit",
  },
  {
    question: "No tengo _____ para el cine.",
    correct: "guita",
    options: ["mate", "che", "dale", "vos"],
    explanation: "'Guita' is money - you need money for cinema",
  },
  {
    question: "Mañana tengo que ir al _____.",
    correct: "laburo",
    options: ["che", "boludo", "dale", "mate"],
    explanation: "You 'go to' work, not the others",
  },
  {
    question: "_____ sos muy inteligente.",
    correct: "Vos",
    options: ["Che", "Mate", "Dale", "Guita"],
    explanation: "'Vos' is the subject pronoun 'you'",
  },
  {
    question: "Tomá el _____ hasta el centro.",
    correct: "colectivo",
    options: ["mate", "asado", "quilombo", "fiaca"],
    explanation: "You 'take' the bus (colectivo) to get places",
  },
  {
    question: "Tengo re _____ hoy.",
    correct: "fiaca",
    options: ["bondi", "subte", "cana", "birra"],
    explanation: "'Fiaca' means laziness - you 'have' laziness",
  },
  {
    question: "Vamos a _____ unas empanadas.",
    correct: "morfar",
    options: ["laburo", "bondi", "quilombo", "fiaca"],
    explanation: "'Morfar' is a verb (to eat) - others are nouns",
  },
  {
    question: "Esa peli está re _____.",
    correct: "copada",
    options: ["mate", "guita", "bondi", "cana"],
    explanation: "'Copada' is an adjective - movie 'is' cool",
  },
  {
    question: "Estoy _____ de este trabajo.",
    correct: "podrido",
    options: ["mate", "asado", "bondi", "laburo"],
    explanation: "'Podrido' means fed up - you're fed up 'of' something",
  },
  {
    question: "_____, no te preocupes.",
    correct: "Tranqui",
    options: ["Mate", "Guita", "Bondi", "Subte"],
    explanation: "'Tranqui' means relax - others are nouns",
  },
  {
    question: "Che, _____ un toque que ya vengo.",
    correct: "esperá",
    options: ["mate", "guita", "fiaca", "bondi"],
    explanation: "'Esperá' is a command (wait) - others are nouns",
  },
  {
    question: "¿Vos _____ ir a la cancha?",
    correct: "querés",
    options: ["mate", "asado", "dale", "che"],
    explanation: "'Querés' is a verb (want) - fits with question",
  },
  {
    question: "Me compré un _____ de chocolate.",
    correct: "alfajor",
    options: ["mate", "laburo", "quilombo", "fiaca"],
    explanation: "'Alfajor' is a food item you buy",
  },
  {
    question: "Vamos a la _____ el domingo.",
    correct: "cancha",
    options: ["fiaca", "guita", "birra", "cana"],
    explanation: "'Cancha' is a place (stadium) you go to",
  },
  {
    question: "Tengo buena _____ con ese pibe.",
    correct: "onda",
    options: ["mate", "bondi", "subte", "cana"],
    explanation: "You have good 'vibes/wave' (onda) with someone",
  },
  {
    question: "Ese tipo es re _____.",
    correct: "gil",
    options: ["mate", "bondi", "asado", "subte"],
    explanation: "'Gil' is an adjective (fool/naive)",
  },
  {
    question: "Vamos a tomar una _____ con los pibes.",
    correct: "birra",
    options: ["fiaca", "quilombo", "laburo", "cana"],
    explanation: "You 'drink' a beer (birra)",
  },
  {
    question: "Siempre _____ fruta ese chabón.",
    correct: "manda",
    options: ["mate", "asado", "bondi", "guita"],
    explanation: "'Manda' is a verb - he 'sends' BS",
  },
  {
    question: "Pasame tu _____ que te llamo.",
    correct: "celu",
    options: ["mate", "asado", "quilombo", "fiaca"],
    explanation: "You call someone on their 'cell phone'",
  },
  {
    question: "¿Vos _____ dónde está la parrilla?",
    correct: "sabés",
    options: ["mate", "guita", "dale", "che"],
    explanation: "'Sabés' is a verb (know) - question needs verb",
  },
  {
    question: "Este _____ está buenísimo.",
    correct: "choripán",
    options: ["laburo", "quilombo", "fiaca", "bondi"],
    explanation: "Food 'tastes' good - choripán is food",
  },
  {
    question: "Esa _____ es re simpática.",
    correct: "piba",
    options: ["mate", "asado", "bondi", "fiaca"],
    explanation: "'Piba' is a person (girl) who can be nice",
  },
  {
    question: "Vivo en un _____ en Palermo.",
    correct: "departamento",
    options: ["mate", "asado", "bondi", "laburo"],
    explanation: "You 'live in' an apartment (departamento)",
  },
  {
    question: "¿_____ para el centro conmigo?",
    correct: "Venís",
    options: ["Mate", "Guita", "Dale", "Fiaca"],
    explanation: "'Venís' is a verb (coming) - question needs verb",
  },
  {
    question: "Soy _____ de Boca desde chico.",
    correct: "hincha",
    options: ["mate", "asado", "bondi", "laburo"],
    explanation: "'Hincha' means fan - you're a fan of a team",
  },
  {
    question: "Compremos _____ en la panadería.",
    correct: "facturas",
    options: ["quilombo", "fiaca", "laburo", "bondi"],
    explanation: "You 'buy' pastries (facturas) at bakery",
  },
  {
    question: "_____ llegué a casa.",
    correct: "Recién",
    options: ["Mate", "Guita", "Bondi", "Fiaca"],
    explanation: "'Recién' means just now - time expression",
  },
  {
    question: "Es la _____ lo que te digo.",
    correct: "posta",
    options: ["mate", "guita", "fiaca", "birra"],
    explanation: "'La posta' means the truth",
  },
  {
    question: "_____ acá que te muestro algo.",
    correct: "Vení",
    options: ["Mate", "Guita", "Bondi", "Laburo"],
    explanation: "'Vení' is a command (come here)",
  },
  {
    question: "Hace un día re _____.",
    correct: "lindo",
    options: ["mate", "bondi", "asado", "laburo"],
    explanation: "'Lindo' is adjective - day is 'nice/pretty'",
  },
  {
    question: "No tengo ni un _____.",
    correct: "mango",
    options: ["che", "dale", "vos", "fiaca"],
    explanation: "'Mango' is slang for peso (money)",
  },
  {
    question: "Mi _____ me prestó el auto.",
    correct: "viejo",
    options: ["mate", "bondi", "asado", "laburo"],
    explanation: "'Viejo' means dad/old man - person who lends",
  },
  {
    question: "Estamos al _____ con este examen.",
    correct: "horno",
    options: ["mate", "bondi", "asado", "laburo"],
    explanation: "'Al horno' means in trouble - expression",
  },
  {
    question: "_____ las pilas que llegamos tarde.",
    correct: "Poné",
    options: ["Mate", "Guita", "Bondi", "Laburo"],
    explanation: "'Poné' is a command - put/get going",
  },
  {
    question: "Voy al _____ a comprar agua.",
    correct: "kiosco",
    options: ["mate", "asado", "laburo", "quilombo"],
    explanation: "'Kiosco' is a place (shop) where you buy things",
  },
  {
    question: "Ese reloj es re _____.",
    correct: "trucho",
    options: ["mate", "bondi", "asado", "laburo"],
    explanation: "'Trucho' is adjective - watch is 'fake'",
  },
  {
    question: "La _____ me paró en la esquina.",
    correct: "cana",
    options: ["mate", "guita", "fiaca", "birra"],
    explanation: "'Cana' means police - they can stop you",
  },
  {
    question: "Vamos al _____ esta noche.",
    correct: "boliche",
    options: ["mate", "laburo", "asado", "quilombo"],
    explanation: "'Boliche' is a place (club) you go to at night",
  },
  {
    question: "No me rompas las _____.",
    correct: "bolas",
    options: ["mate", "guita", "birra", "fiaca"],
    explanation: "Expression: don't break my 'balls' (don't annoy)",
  },
  {
    question: "_____ es el mejor de la historia.",
    correct: "Messi",
    options: ["Mate", "Bondi", "Asado", "Laburo"],
    explanation: "Messi is a person (football player)",
  },
  {
    question: "Hacemos un _____ de fútbol mañana.",
    correct: "picado",
    options: ["mate", "asado", "bondi", "laburo"],
    explanation: "'Picado' is a pickup game - you 'make/have' one",
  },
  {
    question: "Tomá el _____ hasta Retiro.",
    correct: "subte",
    options: ["mate", "asado", "quilombo", "fiaca"],
    explanation: "'Subte' is transportation (subway) you take",
  },
  {
    question: "Está re _____ esa situación.",
    correct: "zarpada",
    options: ["mate", "bondi", "asado", "laburo"],
    explanation: "'Zarpada' is adjective - situation is 'crazy'",
  },
  {
    question: "Vos _____ razón en esto.",
    correct: "tenés",
    options: ["mate", "guita", "dale", "che"],
    explanation: "'Tenés' is verb (have) - you have reason",
  },
  {
    question: "Llevo paraguas por las _____.",
    correct: "dudas",
    options: ["mate", "guita", "birra", "fiaca"],
    explanation: "'Por las dudas' = just in case (expression)",
  },
  {
    question: "Ese _____ siempre llega tarde.",
    correct: "chabón",
    options: ["mate", "asado", "bondi", "laburo"],
    explanation: "'Chabón' is a person (guy) who arrives",
  },
];

export function shuffleArray(array) {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
